nodes:
- name: docker
  driver: docker
  endpoint: unix:///var/run/docker.sock
  platforms:
  - architecture: amd64
    os: linux

- name: docker-container
  driver: docker-container
  endpoint: unix:///var/run/docker.sock
  platforms:
  - architecture: amd64
    os: linux

- name: podman
  driver: podman
  driverOpts:
    rootless: "true"
  platforms:
  - architecture: amd64
    os: linux
